channels:
  - conda-forge
  - defaults
dependencies:
  - appnope
  - asttokens
  - backcall
  - backports
  - backports.functools_lru_cache
  - ca-certificates
  - certifi
  - comm
  - debugpy
  - decorator
  - executing
  - importlib-metadata
  - importlib_metadata
  - ipykernel
  - ipython
  - jedi
  - jupyter_client
  - jupyter_core
  - libcxx
  - libffi
  - libsodium
  - matplotlib-inline
  - ncurses
  - nest-asyncio
  - openssl
  - packaging
  - parso
  - pexpect
  - pickleshare
  - pip
  - platformdirs
  - prompt-toolkit
  - prompt_toolkit
  - psutil
  - ptyprocess
  - pure_eval
  - pygments
  - python
  - python-dateutil
  - python_abi
  - pyzmq
  - readline
  - setuptools
  - six
  - sqlite
  - stack_data
  - tk
  - tornado
  - traitlets
  - typing-extensions
  - typing_extensions
  - wcwidth
  - wheel
  - xz
  - zeromq
  - zipp
  - zlib
  - pip:
      - aiohttp==3.8.4
      - aiosignal==1.3.1
      - alpha-vantage==2.3.1
      - altair==4.2.2
      - appdirs==1.4.4
      - async-timeout==4.0.2
      - attrs==22.2.0
      - beautifulsoup4==4.12.2
      - blinker==1.6.1
      - cachetools==5.3.0
      - cffi==1.15.1
      - charset-normalizer==3.1.0
      - chart-studio==1.1.0
      - click==8.1.3
      - colorlover==0.3.0
      - contourpy==1.0.7
      - cpi==1.0.17
      - cryptography==40.0.1
      - cufflinks==0.17.3
      - cycler==0.11.0
      - entrypoints==0.4
      - fonttools==4.39.3
      - frozendict==2.3.7
      - frozenlist==1.3.3
      - gitdb==4.0.10
      - gitpython==3.1.31
      - html5lib==1.1
      - idna==3.4
      - importlib-resources==5.12.0
      - inflection==0.5.1
      - ipywidgets==8.0.6
      - jinja2==3.1.2
      - joblib==1.2.0
      - jsonschema==4.17.3
      - jupyterlab-widgets==3.0.7
      - kiwisolver==1.4.4
      - lxml==4.9.2
      - markdown-it-py==2.2.0
      - markupsafe==2.1.2
      - matplotlib==3.7.1
      - mdurl==0.1.2
      - more-itertools==9.1.0
      - multidict==6.0.4
      - multitasking==0.0.11
      - nasdaq-data-link==1.0.4
      - numpy==1.24.2
      - pandas==2.0.0
      - patsy==0.5.3
      - pillow==9.5.0
      - plotly==5.14.1
      - protobuf==3.20.3
      - psycopg2-binary==2.9.6
      - pyarrow==11.0.0
      - pycoingecko==3.1.0
      - pycparser==2.21
      - pydeck==0.8.0
      - pympler==1.0.1
      - pyodbc==4.0.38
      - pyparsing==3.0.9
      - pyrsistent==0.19.3
      - python-dotenv==1.0.0
      - pytz==2023.3
      - pytz-deprecation-shim==0.1.0.post0
      - requests==2.28.2
      - retrying==1.3.4
      - rich==13.3.3
      - scikit-learn==1.2.2
      - scipy==1.10.1
      - seaborn==0.12.2
      - smmap==5.0.0
      - soupsieve==2.4
      - statsmodels==0.13.5
      - stockstats==0.5.2
      - streamlit==1.21.0
      - ta==0.10.2
      - ta-lib==0.4.26
      - tenacity==8.2.2
      - threadpoolctl==3.1.0
      - toml==0.10.2
      - toolz==0.12.0
      - tzdata==2023.3
      - tzlocal==4.3
      - urllib3==1.26.15
      - validators==0.20.0
      - webencodings==0.5.1
      - widgetsnbextension==4.0.7
      - yarl==1.8.2
      - yfinance==0.2.17
